// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTiIOx6iAAoewMYp9ppWTEuwQJNiOBxb8',
    appId: '1:992025434149:web:2106e7c922fe4819ac47cc',
    messagingSenderId: '992025434149',
    projectId: 'financial-management-app-dash',
    authDomain: 'financial-management-app-dash.firebaseapp.com',
    storageBucket: 'financial-management-app-dash.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEWUFONHhZLYeGYoxFIC3nj65flQfJQ-M',
    appId: '1:992025434149:android:c49f6059cd2ec4caac47cc',
    messagingSenderId: '992025434149',
    projectId: 'financial-management-app-dash',
    storageBucket: 'financial-management-app-dash.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrQJfJV79yTacjgPjkIL_jy9TL6MsCGMU',
    appId: '1:992025434149:ios:ae289bf1fb4f13d0ac47cc',
    messagingSenderId: '992025434149',
    projectId: 'financial-management-app-dash',
    storageBucket: 'financial-management-app-dash.appspot.com',
    iosClientId: '992025434149-15fjjtnrgr54n69mj7vss677p8h4uglo.apps.googleusercontent.com',
    iosBundleId: 'com.example.financeManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrQJfJV79yTacjgPjkIL_jy9TL6MsCGMU',
    appId: '1:992025434149:ios:ae289bf1fb4f13d0ac47cc',
    messagingSenderId: '992025434149',
    projectId: 'financial-management-app-dash',
    storageBucket: 'financial-management-app-dash.appspot.com',
    iosClientId: '992025434149-15fjjtnrgr54n69mj7vss677p8h4uglo.apps.googleusercontent.com',
    iosBundleId: 'com.example.financeManagementApp',
  );
}
